import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider } from "@/store/globalContext";
import { ModalProvider } from "@/store/modalContext";
import ReusableModal from "@/components/molecules/ReusableModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <GlobalContextProvider>
        <ModalProvider>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
            {children}
            <ReusableModal />
          </body>
        </ModalProvider>
      </GlobalContextProvider>
    </html>
  );
}
